apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-freezer.fullname" . }}
  labels:
    {{- include "kube-freezer.labels" . | nindent 4 }}
  annotations:
    # Ensure ClusterRole is created before cert-generator Job
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-9"
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["{{ include "kube-freezer.fullname" . }}-config"]
    verbs: ["get", "watch", "list", "patch", "update"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: 
      - "{{ include "kube-freezer.fullname" . }}-api-keys"
      - "{{ include "kube-freezer.fullname" . }}-tls"
    verbs: ["get", "list", "patch", "update"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames:
      - "{{ include "kube-freezer.fullname" . }}-templates"
      - "{{ include "kube-freezer.fullname" . }}-notifications"
      - "{{ include "kube-freezer.fullname" . }}-exemptions"
      - "kube-freezer-schedules"
      - "kube-freezer-history"
    verbs: ["get", "watch", "list", "patch", "update"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations"]
    resourceNames: ["{{ include "kube-freezer.fullname" . }}"]
    verbs: ["get", "list", "patch", "update"]
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]

