{{- if .Values.templates.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-freezer.fullname" . }}-templates
  namespace: {{ include "kube-freezer.namespace" . }}
  labels:
    {{- include "kube-freezer.labels" . | nindent 4 }}
data:
  templates: |
{{- if .Values.templates.customTemplates }}
{{ .Values.templates.customTemplates | toYaml | indent 4 }}
{{- else }}
[]
{{- end }}
{{- end }}

