apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kube-freezer.fullname" . }}-configmap-creator
  namespace: {{ include "kube-freezer.namespace" . }}
  labels:
    {{- include "kube-freezer.labels" . | nindent 4 }}
  annotations:
    # Ensure RoleBinding is created before cert-generator Job
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-8"
    "helm.sh/hook-delete-policy": before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kube-freezer.fullname" . }}-configmap-creator
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-freezer.serviceAccountName" . }}
    namespace: {{ include "kube-freezer.namespace" . }}

