{{- if not .Values.certificate.useCertManager }}
{{- if .Values.certificate.manual }}
{{- $secretName := include "kube-freezer.fullname" . }}
{{- $namespace := include "kube-freezer.namespace" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}-tls
  namespace: {{ $namespace }}
  labels:
    {{- include "kube-freezer.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  # Manual certificates provided via values.yaml
  tls.crt: {{ .Values.certificate.cert | b64enc }}
  tls.key: {{ .Values.certificate.key | b64enc }}
{{- else }}
# Secret will be created by the certificate generation Job (job-cert-generator.yaml)
# This prevents Helm from trying to create an empty secret that conflicts with the Job
{{- end }}
{{- end }}

