{{- if not .Values.certificate.useCertManager }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-freezer.fullname" . }}-tls
  namespace: {{ include "kube-freezer.namespace" . }}
  labels:
    {{- include "kube-freezer.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  # These will be populated by the certificate generation script
  tls.crt: ""
  tls.key: ""
{{- end }}

