apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "kube-freezer.fullname" . }}
  labels:
    {{- include "kube-freezer.labels" . | nindent 4 }}
webhooks:
  - name: {{ include "kube-freezer.fullname" . }}.admission.kubefreezer.io
    admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      service:
        name: {{ include "kube-freezer.fullname" . }}-backend
        namespace: {{ include "kube-freezer.namespace" . }}
        path: "/admission"
        port: 443
      {{- if .Values.certificate.caBundle }}
      caBundle: {{ .Values.certificate.caBundle | quote }}
      {{- else if .Values.certificate.manual }}
      caBundle: {{ .Values.certificate.cert | b64enc | quote }}
      {{- else }}
      caBundle: ""  # Will be populated by certificate generation Job (job-cert-generator.yaml)
      {{- end }}
    rules:
      {{- range .Values.webhook.rules }}
      - apiGroups: {{ .apiGroups | toJson }}
        apiVersions: {{ .apiVersions | toJson }}
        operations: {{ .operations | toJson }}
        resources: {{ .resources | toJson }}
        {{- if .scope }}
        scope: {{ .scope | quote }}
        {{- end }}
      {{- end }}
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    sideEffects: None
    timeoutSeconds: {{ .Values.webhook.timeoutSeconds }}
    namespaceSelector:
      matchExpressions:
        - key: kubefreezer.io/exempt
          operator: NotIn
          values: ["true"]

